/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import identifikasisidikjarilevenbergbackpro.FPImageViewer;
import identifikasisidikjarilevenbergbackpro.FeatureExtractor;
import identifikasisidikjarilevenbergbackpro.FingerPrintImage;
import identifikasisidikjarilevenbergbackpro.Input;
import identifikasisidikjarilevenbergbackpro.BackPropagationTrainer;
import identifikasisidikjarilevenbergbackpro.LevenbergMarquardtTrainer;
import identifikasisidikjarilevenbergbackpro.NetworkSetting;
import identifikasisidikjarilevenbergbackpro.NetworkWriter;
import identifikasisidikjarilevenbergbackpro.PixelsReader;
import identifikasisidikjarilevenbergbackpro.Preprocessor;
import identifikasisidikjarilevenbergbackpro.TrainingSamples;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;
import utils.ExtensionFileFilter;

 
public class FormTraining extends javax.swing.JFrame 
{
    private TrainingSamples ts;
    private JFileChooser flchooser = new JFileChooser();
    /**
     * Creates new form FormTraining
     */
    public FormTraining() 
    {
        initComponents();
        setTitle("Pelatihan Sidik Jari:Dengan Algoritma Levenberg-Marquardt dan BackPropagation");
        utils.Util.TengahWindow(this);
        setResizable(false);
        
        ts = new TrainingSamples();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgAlgoritma = new javax.swing.ButtonGroup();
        jbtnLatihJaringan = new javax.swing.JButton();
        jbtnTutup = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblTrainset = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbtnBrowse = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTxtMaxEpoch = new javax.swing.JTextField();
        jTxtErrTolerance = new javax.swing.JTextField();
        jTxtMaxHidden = new javax.swing.JTextField();
        jTxtLearningRate = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jlblMSE = new javax.swing.JLabel();
        jlblEpoch = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jRbtnLevenMar = new javax.swing.JRadioButton();
        jRbtnBackPro = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jlblViewImage = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlblRTVR = new javax.swing.JLabel();
        jlblKepadatanRidge = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnLatihJaringan.setText("Latih Jaringan");
        jbtnLatihJaringan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLatihJaringanActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnLatihJaringan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 810, 46));

        jbtnTutup.setText("Tutup");
        jbtnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTutupActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnTutup, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 480, 136, 46));

        jTblTrainset.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTblTrainset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblTrainsetMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTblTrainset);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 134, 560, 219));

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 460, 1000, 10));

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 820, 10));

        jLabel2.setText("Tot. Data Latih");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        jLabel3.setText("0");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        jbtnBrowse.setText("Browse..");
        jbtnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 125, 34));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Parameter JST"));

        jLabel4.setText("Max. Epoch");

        jLabel8.setText("Learning Rate:");

        jLabel10.setText("Error Tolerance:");

        jLabel11.setText("Maksimum Hidden:");

        jTxtMaxEpoch.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtMaxEpoch.setText("1000");
        jTxtMaxEpoch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtMaxEpochActionPerformed(evt);
            }
        });

        jTxtErrTolerance.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtErrTolerance.setText("0.001");

        jTxtMaxHidden.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtMaxHidden.setText("8");
        jTxtMaxHidden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtMaxHiddenActionPerformed(evt);
            }
        });

        jTxtLearningRate.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtLearningRate.setText("0.5");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTxtMaxEpoch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jTxtErrTolerance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jTxtLearningRate, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jTxtMaxHidden))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtMaxHidden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtMaxEpoch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtErrTolerance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtLearningRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 360, -1, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(777, 374, 21, 82));

        jLabel12.setText("MSE    :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 400, -1, -1));

        jLabel13.setText("Epoch  :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 420, -1, -1));

        jlblMSE.setText("0.0");
        getContentPane().add(jlblMSE, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 400, -1, -1));

        jlblEpoch.setText("0.0");
        getContentPane().add(jlblEpoch, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 420, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 958, 10));

        jLabel1.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel1.setText("PELATIHAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Algoritma"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgAlgoritma.add(jRbtnLevenMar);
        jRbtnLevenMar.setText("Levenberg-Marquardt ");
        jPanel4.add(jRbtnLevenMar, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 18, -1, -1));

        bgAlgoritma.add(jRbtnBackPro);
        jRbtnBackPro.setText("Backpropagation");
        jPanel4.add(jRbtnBackPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 560, 50));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblViewImage.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.add(jlblViewImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 250));

        jLabel5.setText("RTVR:");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLabel6.setText("Kepadatan Ridge:");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        jlblRTVR.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblRTVR.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblRTVR.setText("0");
        jlblRTVR.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel5.add(jlblRTVR, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 120, -1));

        jlblKepadatanRidge.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblKepadatanRidge.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblKepadatanRidge.setText("0");
        jPanel5.add(jlblKepadatanRidge, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 120, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 380, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private int ShowDialogOpenImage()
    {    
        FileFilter filter1 = new ExtensionFileFilter("Bitmap", new String[] { "BMP"});
        flchooser.setFileFilter(filter1);
        flchooser.setMultiSelectionEnabled(true);
        int tanggapan = flchooser.showOpenDialog(this);   
        return tanggapan;
    }
    
        public void setStatus(String mse,String epoch)
{
    jlblMSE.setText(mse);
    jlblEpoch.setText(epoch);
}
    
    private void jbtnLatihJaringanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLatihJaringanActionPerformed
        try {
            // TODO add your handling code here:
            
            NetworkSetting ns = new NetworkSetting();
            ns.setErrTolerance(Double.parseDouble(jTxtErrTolerance.getText()));
            ns.setNNeuronOutput(1);
            ns.setNNeuronHidden(Integer.parseInt(jTxtMaxHidden.getText()));
            ns.setLearningRate(Double.parseDouble(jTxtLearningRate.getText()));
            ns.setMaxEpoch(Integer.parseInt(jTxtMaxEpoch.getText()));            
            System.out.println("Training Siap Dimulai...");
            
            NetworkWriter.writeSetting("setting", "network", ns);
            
            if (jRbtnLevenMar.isSelected())
            {
                LevenbergMarquardtTrainer lmt = new LevenbergMarquardtTrainer(ts, this, ns);
                lmt.train();
            }else if (jRbtnBackPro.isSelected())
            {
                BackPropagationTrainer jsttrainer = new  BackPropagationTrainer(ts, this,ns);
                jsttrainer.train();
            }
        } catch (IOException ex) {
            Logger.getLogger(FormTraining.class.getName()).log(Level.SEVERE, null, ex);
        }
       

         
    }//GEN-LAST:event_jbtnLatihJaringanActionPerformed

    private void jbtnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTutupActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbtnTutupActionPerformed

    private void jbtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseActionPerformed
        // TODO add your handling code here:
        int tanggapan = ShowDialogOpenImage();
        if(tanggapan==JFileChooser.APPROVE_OPTION)
        {
            BufferedImage img=null;
            try{

                for(int i=0;i<flchooser.getSelectedFiles().length;i++)
                {
                    String name =flchooser.getSelectedFiles()[i].getAbsoluteFile().getName();
                    String arrstr[] = name.split("_");

                    img = ImageIO.read(flchooser.getSelectedFiles()[i].getAbsoluteFile());
                    ImageIcon imgicon = new ImageIcon(img);

                    PixelsReader pxlsLoad = new PixelsReader();
                    pxlsLoad.readPixelsFrom(imgicon);
                    FingerPrintImage fpimage = pxlsLoad.getFPImage();
                    /*

                    *
                    *
                    */
                   
                    ts.addFPImage(fpimage, flchooser.getSelectedFiles()[i].getAbsolutePath(), arrstr[0]);

                }
                showFilesImages();

            }catch(IOException ex)
            {

            }
        }
    }//GEN-LAST:event_jbtnBrowseActionPerformed
public void showMessage(String pesan)
{
   JOptionPane.showMessageDialog(this, pesan,"Peringatan",JOptionPane.WARNING_MESSAGE);
}

    private void showFilesImages()
    {
        String[] header = new String[]{"No","Image FileName","Target"};
        String[][] data = new String[ts.getTotalFingerPrint()][header.length];
        for(int i=0;i<ts.getTotalFingerPrint();i++)
        {     
                String ffname = ts.getFingerPrintImage(i).getName();
                // System.out.println("FFName " + ffname);
                data[i][0] = String.valueOf(i+1);
                data[i][1] = ts.getFileNames(i);
                data[i][2] = ffname;
         }
            jTblTrainset.setModel(new DefaultTableModel(data, header));

    }
    private void jTxtMaxEpochActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtMaxEpochActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtMaxEpochActionPerformed

    private void jTxtMaxHiddenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtMaxHiddenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtMaxHiddenActionPerformed

    private void jTblTrainsetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblTrainsetMouseClicked
        // TODO add your handling code here:
      int baris = jTblTrainset.rowAtPoint(evt.getPoint());    
      FingerPrintImage fpimg = ts.getFingerPrintImage(baris);
      FPImageViewer fpiv = new FPImageViewer();
      fpiv.setImage(fpimg);
      fpiv.setViewer(jlblViewImage);
      fpiv.viewImageDefault();
      
      Preprocessor prep = new Preprocessor(fpimg.getHeight(), fpimg.getWidth());
      fpimg = prep.binarize(fpimg);
           
      FeatureExtractor fe = new  FeatureExtractor();
      Input inp =fe.extract(fpimg);
      
      jlblRTVR.setText(String.format("%.4f", inp.getValue(0)));
      jlblKepadatanRidge.setText(String.format("%.4f", inp.getValue(2)));
     
      fpiv.viewImageOutput();
        
    }//GEN-LAST:event_jTblTrainsetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTraining.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTraining.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTraining.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTraining.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTraining().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgAlgoritma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRbtnBackPro;
    private javax.swing.JRadioButton jRbtnLevenMar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTblTrainset;
    private javax.swing.JTextField jTxtErrTolerance;
    private javax.swing.JTextField jTxtLearningRate;
    private javax.swing.JTextField jTxtMaxEpoch;
    private javax.swing.JTextField jTxtMaxHidden;
    private javax.swing.JButton jbtnBrowse;
    private javax.swing.JButton jbtnLatihJaringan;
    private javax.swing.JButton jbtnTutup;
    private javax.swing.JLabel jlblEpoch;
    private javax.swing.JLabel jlblKepadatanRidge;
    private javax.swing.JLabel jlblMSE;
    private javax.swing.JLabel jlblRTVR;
    private javax.swing.JLabel jlblViewImage;
    // End of variables declaration//GEN-END:variables
}
