/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 
package ui;
 
 
import identifikasisidikjarilevenbergbackpro.FPImageViewer;
import identifikasisidikjarilevenbergbackpro.FingerPrintIdentifier;
import identifikasisidikjarilevenbergbackpro.FingerPrintImage;
import identifikasisidikjarilevenbergbackpro.PixelsReader;
import identifikasisidikjarilevenbergbackpro.TrainingSamples;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
 
import javax.swing.table.DefaultTableModel;
import utils.ExtensionFileFilter;
import utils.Util;
 
public class FormIdentifyFingerPrint extends javax.swing.JFrame 
{
    private JFileChooser flchooser = new JFileChooser();
    private TrainingSamples ujisamples;
   
 
    /** Creates new form FormRecogniseFace */
    public FormIdentifyFingerPrint() {
        initComponents();
        Util.TengahWindow(this);
        setResizable(false);
        setTitle("Identifikasi Jenis Kelamin ");
        ujisamples = new TrainingSamples();
        showFilesImages();
    }

    
    private void showFilesImages()
    {
      
        String[] header = new String[]{"No","Image FileName","Result"};
        String[][] data = new String[ujisamples.getTotalFingerPrint()][header.length];
        for(int i=0;i<ujisamples.getTotalFingerPrint();i++)
        {     
            String ffname = ujisamples.getFingerPrintImage(i).getName();
            // System.out.println("FFName " + ffname);
            data[i][0] = String.valueOf(i+1);
            data[i][1] = ujisamples.getFileNames(i);
          
              data[i][2] = ffname;
           
        
        }
        jtblDataUji.setModel(new DefaultTableModel(data, header));
}
    
    private int ShowDialogOpenImage()
   {    
        FileFilter filter1 = new ExtensionFileFilter("Image Files", new String[] { "BMP","JPG","JPEG","PNG"});
        flchooser.setFileFilter(filter1);
        flchooser.setMultiSelectionEnabled(true);
        int tanggapan = flchooser.showOpenDialog(this);   
        return tanggapan;
   }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlblBijiSawit = new javax.swing.JLabel();
        jlblHasil = new javax.swing.JLabel();
        jbtnKenali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblDataUji = new javax.swing.JTable();
        jbtnBrowse = new javax.swing.JButton();
        jbtnTutup = new javax.swing.JButton();
        jRbtnLM = new javax.swing.JRadioButton();
        jRbtnBP = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("IDENTIFIKASI JENIS KELAMIN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(393, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 30));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlblBijiSawit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblBijiSawit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblBijiSawitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblBijiSawit, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblBijiSawit, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        jlblHasil.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblHasil.setForeground(new java.awt.Color(255, 0, 0));
        jlblHasil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblHasil.setText(".............");
        jlblHasil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jlblHasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, 260, 160));

        jbtnKenali.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnKenali.setText("IDENTIFY FINGER PRINT");
        jbtnKenali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKenaliActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnKenali, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 500, 40));

        jtblDataUji.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblDataUji.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblDataUjiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblDataUji);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 620, 280));

        jbtnBrowse.setText("Browse..");
        jbtnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 110, 40));

        jbtnTutup.setText("Tutup");
        jbtnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTutupActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnTutup, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 730, 620, 40));

        buttonGroup2.add(jRbtnLM);
        jRbtnLM.setText("Bobot LevenvergMarquardt");
        jRbtnLM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbtnLMActionPerformed(evt);
            }
        });
        getContentPane().add(jRbtnLM, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        buttonGroup2.add(jRbtnBP);
        jRbtnBP.setText("Bobot Backpropagation");
        jRbtnBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbtnBPActionPerformed(evt);
            }
        });
        getContentPane().add(jRbtnBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 153));
        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jbtnKenaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnKenaliActionPerformed
// TODO add your handling code here: 
     int typeofweights = -1;
     
     if (jRbtnLM.isSelected())
     {
         typeofweights = FingerPrintIdentifier.LEVENBERGMARQUARDT_WEIGHTS;
     }else if (jRbtnBP.isSelected())
     {
         typeofweights = FingerPrintIdentifier.BACKPROPAGATION_WEIGHTS;
     }
     
     for(int i=0;i<ujisamples.getTotalFingerPrint();i++) 
     {
        FingerPrintImage fpimg = ujisamples.getFingerPrintImage(i);
        FingerPrintIdentifier fpi= new FingerPrintIdentifier(fpimg,typeofweights );
        String result = fpi.GetID();
        jlblHasil.setText(result);
        ujisamples.getFingerPrintImage(i).SetName(result);
     }
     showFilesImages();
   
}//GEN-LAST:event_jbtnKenaliActionPerformed

    private void jbtnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTutupActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_jbtnTutupActionPerformed

    private void jbtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseActionPerformed
        // TODO add your handling code here:
            int tanggapan = ShowDialogOpenImage(); 
            if(tanggapan==JFileChooser.APPROVE_OPTION)
            {
                BufferedImage img=null;
             
                try
                {            
                     FingerPrintImage fpiimg=null ;
                     ujisamples.clear();
                     
                     for(int i=0;i<flchooser.getSelectedFiles().length;i++) 
                     {
                         img = ImageIO.read(flchooser.getSelectedFiles()[i].getAbsoluteFile());                
                         ImageIcon imgicon = new ImageIcon(img); 
                         PixelsReader pxlsLoad = new PixelsReader();
                         pxlsLoad.readPixelsFrom(imgicon);
                         fpiimg = pxlsLoad.getFPImage();
                         String name = flchooser.getSelectedFiles()[i].getName();
                         // System.out.println(name);                 
                         ujisamples.addFPImage(fpiimg, flchooser.getSelectedFiles()[i].getAbsolutePath(), "--???--");
                     }

               


                }catch(IOException ex)
                {

                }  
                showFilesImages();
            }
    }//GEN-LAST:event_jbtnBrowseActionPerformed

    private void jlblBijiSawitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblBijiSawitMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jlblBijiSawitMouseClicked

    private void jtblDataUjiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblDataUjiMouseClicked
        // TODO add your handling code here:
        int baris = jtblDataUji.rowAtPoint(evt.getPoint());
        FingerPrintImage fpimage = ujisamples.getFingerPrintImage(baris);        
        FPImageViewer fiv =new FPImageViewer();               
        fiv.setImage(fpimage);
        fiv.setViewer(jlblBijiSawit);
        fiv.viewImageDefault();;
        
        jlblHasil.setText(fpimage.getName());
    }//GEN-LAST:event_jtblDataUjiMouseClicked

    private void jRbtnLMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbtnLMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRbtnLMActionPerformed

    private void jRbtnBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbtnBPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRbtnBPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormIdentifyFingerPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormIdentifyFingerPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormIdentifyFingerPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormIdentifyFingerPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FormIdentifyFingerPrint().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRbtnBP;
    private javax.swing.JRadioButton jRbtnLM;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnBrowse;
    private javax.swing.JButton jbtnKenali;
    private javax.swing.JButton jbtnTutup;
    private javax.swing.JLabel jlblBijiSawit;
    private javax.swing.JLabel jlblHasil;
    private javax.swing.JTable jtblDataUji;
    // End of variables declaration//GEN-END:variables
}
