/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

 
public class FormMain extends javax.swing.JFrame {

    /**
     * Creates new form FormMain
     */
    public FormMain() 
    {
        initComponents();
        utils.Util.TengahWindow(this);
        setResizable(false);
        setTitle("Menu Utama");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnShowFormLatihSidikJari = new javax.swing.JButton();
        jbtnShowFormKlasifikasiSidikJari = new javax.swing.JButton();
        jbtnKeluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnShowFormLatihSidikJari.setText("Latih Data Sidik Jari");
        jbtnShowFormLatihSidikJari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnShowFormLatihSidikJariActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnShowFormLatihSidikJari, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 270, 80));

        jbtnShowFormKlasifikasiSidikJari.setText("Identifikasi Jenis Kelamin");
        jbtnShowFormKlasifikasiSidikJari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnShowFormKlasifikasiSidikJariActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnShowFormKlasifikasiSidikJari, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 270, 80));

        jbtnKeluar.setText("Keluar");
        jbtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 270, 70));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("DENGAN MENGGUNAKAN LEVENBERG-MARQUART DAN BACKPROPAGATION NEURAL NETWORK");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("BERDASARKAN SIDIK JARI");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 760, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("IDENTIFIKASI JENIS KELAMIN ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnShowFormLatihSidikJariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnShowFormLatihSidikJariActionPerformed
        // TODO add your handling code here:
        FormTraining frmTraining = new FormTraining();
        frmTraining.setVisible(true);
    }//GEN-LAST:event_jbtnShowFormLatihSidikJariActionPerformed

    private void jbtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnKeluarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbtnKeluarActionPerformed

    private void jbtnShowFormKlasifikasiSidikJariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnShowFormKlasifikasiSidikJariActionPerformed
        // TODO add your handling code here:
        FormIdentifyFingerPrint frmIdentify = new FormIdentifyFingerPrint();
        frmIdentify.setVisible(true);
    }//GEN-LAST:event_jbtnShowFormKlasifikasiSidikJariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbtnKeluar;
    private javax.swing.JButton jbtnShowFormKlasifikasiSidikJari;
    private javax.swing.JButton jbtnShowFormLatihSidikJari;
    // End of variables declaration//GEN-END:variables
}
